# Change these first
owner: Maxtel-Tecnologia # Your GitHub organization or username, where this repository lives
repo: TrueSafe-Web-Status-Page # The name of this repository

sites:
  - name: TrueSafe Web (https)
    url: https://www.truesafeweb.com.br
    icon: https://www.truesafeweb.com.br/imagens/icons/principal/truesafe.ico
    maxResponseTime: 5000
  - name: TrueSafe Pass (https)
    url: https://www.truesafepass.com.br
    maxResponseTime: 5000    
  - name: TrueSafe Pass Dashboard
    url: https://dashboard.truesafepass.com.br
    maxResponseTime: 5000    
  - name: TrueSafe pagina invalida (index2.php)
    url: https://www.truesafeweb.com.br/index2.php    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.truesafeweb.com.br
  baseUrl: /TrueSafe-Web-Status-Page
  logoUrl: https://www.truesafeweb.com.br/imagens/logo_truesafe.png
  favicon: https://www.truesafeweb.com.br/imagens/icons/principal/truesafe.ico
  name: TrueSafe Web
  introTitle: "Status Page"
  introMessage: Página destinada ao monitoramento e status dos serviços do TrueSafe Web
  theme: light
  navbar:
    - title: Status
      href: /TrueSafe-Web-Status-Page
    - title: Maxtel
      href: https://www.maxtel.com.br
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Incidentes Ativos
  allSystemsOperational: Todos os sistemas estão operacionais
  activeIncidentSummary: Aberto em $DATE com $POSTS postagens
  incidentTitle: Incidente $NUMBER Detalhes
  incidentDetails: Detalhes do Incidente
  incidentFixed: Reparado
  incidentOngoing: Em andamento
  incidentOpenedAt: Aberto em
  incidentClosedAt: Fechado em
  incidentSubscribe: Inscreva-se para atualizações
  incidentViewOnGitHub: Ver no GitHub
  incidentCommentSummary: Postado em $DATE por $AUTHOR
  incidentBack: ← Voltar para todos os incidentes
  pastIncidents: Últimos Incidentes
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS postagens
  liveStatus: Status Atual
  overallUptimeTitle: Tempo de Atividade Geral
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Resposta Média
  sevelDayResponseTime: 7-dias tempo resposta
  responseTimeMs: Tempo resposta (ms)
  up: ativo
  down: não está funcionando
  degraded: Reduzido
  ms: ms
  loading: Carregando
  footer: Maxtel Tecnologia Ltda
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: Duration
  durationMin: $DURATION minutes
  incidentCompleted: Completed
  incidentScheduled: Scheduled
