# Change these first
owner: Maxtel-Tecnologia # Your GitHub organization or username, where this repository lives
repo: TrueSafe-Web-Status-Page # The name of this repository

sites:
  - name: TrueSafe Web Site
    url: $STATUS_SITE
    icon: https://www.truesafeweb.com.br/imagens/icons/principal/truesafe.ico
  - name: TrueSafe App API
    url: $STATUS_APP_API
    icon: https://app.truesafe.com.br/imagens/logo_truesafe.png
  - name: User BD Site
    url: $STATUS_USERBD_SITE
    icon: https://www.truesafeweb.com.br/imagens/icons/principal/truesafe.ico
  - name: User BD Comunics
    url: $STATUS_USERBD_COMUNICS
    icon: https://www.truesafeweb.com.br/imagens/icons/principal/truesafe.ico
  - name: TrueSafe Pass Dashboard
    url: https://dashboard.truesafepass.com.br
    icon: https://www.truesafeweb.com.br/imagens/icons/principal/truesafe.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.truesafeweb.com.br
  # baseUrl: /TrueSafe-Web-Status-Page
  logoUrl: https://www.truesafeweb.com.br/imagens/logo_truesafe.png
  favicon: https://www.truesafeweb.com.br/imagens/icons/principal/truesafe.ico
  name: TrueSafe Web
  introTitle: "Status Services"
  introMessage: Página de monitoramento e status dos serviços do TrueSafe Web
  theme: ocean
  navbar:
    - title: Home
      href: /
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
notifications:
  - type: telegram

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "0 */3 * * *"
  graphs: "10 */3 * * *"
  summary: "10 */3 * * *"
  staticSite: "20 */3 * * *"
  updates: "30 */3 * * *"
  updateTemplate: "0 0 * * *"
  
i18n:
  activeIncidents: Incidentes Ativos
  allSystemsOperational: Todos os sistemas estão OK
  activeIncidentSummary: Aberto em $DATE com $POSTS postagens
  incidentTitle: Incidente $NUMBER Detalhes
  incidentDetails: Detalhes do Incidente
  incidentFixed: Reparado
  incidentOngoing: Em andamento
  incidentOpenedAt: Aberto em
  incidentClosedAt: Fechado em
  incidentSubscribe: Inscreva-se para atualizações
  incidentViewOnGitHub: Ver no GitHub
  incidentCommentSummary: Postado em $DATE por $AUTHOR
  incidentBack: ← Voltar
  pastIncidents: Últimos Incidentes
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS postagens
  liveStatus: Status Atual
  overallUptimeTitle: Tempo de Atividade Geral
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Resposta Média
  sevelDayResponseTime: Últimos Registros
  responseTimeMs: Tempo resposta (ms)
  up: ativo
  down: com problema
  degraded: Degradado
  ms: ms
  loading: Carregando
  footer: Maxtel Tecnologia Ltda
  rateLimitExceededTitle: Limite excedido
  rateLimitExceededIntro: Você excedeu o número de solicitações que pode fazer em uma hora, então terá que esperar antes de acessar este site novamente.
  rateLimitExceededWhatDoesErrorMean: O que esse erro significa?
  rateLimitExceededErrorMeaning: Este site usa a API do GitHub para acessar dados em tempo real sobre o status de nossos sites. Por padrão, o GitHub permite a cada endereço IP 60 solicitações por hora, que você consumiu.
  rateLimitExceededErrorHowCanFix: Como posso corrigir isso?
  rateLimitExceededErrorFix: Você pode esperar por mais uma hora e o limite do seu endereço IP será restaurada.
  rateLimitExceededGeneratePAT: Aprenda a gerar um token de acesso pessoal
  rateLimitExceededHasSet: Você tem um conjunto de tokens de acesso pessoal.
  rateLimitExceededRemoveToken: Remover token
  rateLimitExceededGitHubPAT: Token de acesso pessoal do GitHub
  rateLimitExceededCopyPastePAT: Copie e cole seu token
  rateLimitExceededSaveToken: Salvar token
  errorTitle: Ocorreu um erro
  errorIntro: Ocorreu um erro ao tentar obter os detalhes de status mais recentes.
  errorText: Tente novamente em alguns instantes.
  errorHome: Ir para página inicial
  pastScheduledMaintenance: Manutenções agendadas anteriores
  scheduledMaintenance: Manutenção Agendada
  scheduledMaintenanceSummaryStarted: Comceçou em $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Começa em $DATE por $DURATION minutos
  startedAt: Iniciou em
  startsAt: Inicia em
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Completo
  incidentScheduled: Agendado
