# Change these first
owner: Maxtel-Tecnologia # Your GitHub organization or username, where this repository lives
repo: TrueSafe-Web-Status-Page # The name of this repository

sites:
  - name: TrueSafe Web (https)
    url: https://www.truesafeweb.com.br
  - name: TrueSafe Pass (https)
    url: https://www.truesafepass.com.br
  - name: TrueSafe Pass Dashboard
    url: https://dashboard.truesafepass.com.br

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.truesafeweb.com.br
  baseUrl: /TrueSafe-Web-Status-Page
  logoUrl: https://www.truesafeweb.com.br/imagens/logo_truesafe.png
  name: TrueSafe Web
  introTitle: "Status Page"
  introMessage: Página destinada ao monitoramento e status dos serviços do TrueSafe Web
  navbar:
    - title: Status
      href: /TrueSafe-Web-Status-Page

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
